import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Header from '@/components/layout/Header';
import Footer from '@/components/layout/Footer';
import { fetchPayloadData } from '@/hooks/useDataProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Cruize Control HealthCare',
  description: 'Generated by create next app',
};
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const data = await fetchPayloadData('header-footer')
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header 
          DarkLogo={data?.DarkLogo}
          Phone={data?.Phone}
        />
        {children}
        <Footer
          LightLogo={data?.LightLogo}
          FooterText={data?.FooterText}
          CopyrightString={data?.CopyrightString}
          SocialMediaLinks={data?.socialMediaLinks}
        />
      </body>
    </html>
  );
}
