import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Cruize Control HealthCare Admin',
  description: 'Generated by create next app',
  robots:{
    follow:false,
    index:false
  }
};
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <>
    { children }
  </>
}
